version: '3'

volumes:
  product-node-modules:
  user-node-modules:
  order-node-modules:

networks:
  order-network:
    driver: bridge

services:
  frontend:
    build:
      context: .
    ports:
      - 80:5000
    volumes:
      - ./app:/app
    restart: always
    networks:
      - order-network

  product:
    build:
      context: ../product_service/
    ports:
      - 8081:5000
    volumes:
      - ../product_service/app:/app
      - product-node-modules:/app/node_modules
    restart: always
    networks:
      - order-network

  user:
    build:
      context: ../user_service/
    ports:
      - 8082:5000
    volumes:
      - ../user_service/app:/app
      - user-node-modules:/app/node_modules
    restart: always
    networks:
      - order-network

  order:
    build:
      context: ../order_service/
    ports:
      - 8083:5000
    volumes:
      - ../order_service/app:/app
      - order-node-modules:/app/node_modules
    restart: always
    networks:
      - order-network